# Generated by Django 2.0.7 on 2018-07-24 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
