# Generated by Django 2.0.7 on 2018-07-24 03:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foodi', '0003_auto_20180724_0225'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_eaten', models.DateField()),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foodi.Food')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foodi.User')),
            ],
        ),
        migrations.AddField(
            model_name='food',
            name='users',
            field=models.ManyToManyField(through='foodi.Diary', to='foodi.User'),
        ),
    ]
