# Generated by Django 2.0.7 on 2018-07-24 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodi', '0004_auto_20180724_0309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='serving_unit',
            field=models.CharField(max_length=100),
        ),
    ]
