# Generated by Django 2.0.7 on 2018-07-24 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodi', '0005_auto_20180724_1724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='serving_unit',
            field=models.CharField(max_length=500),
        ),
    ]
