# Generated by Django 2.0.7 on 2018-07-25 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodi', '0009_auto_20180725_0124'),
    ]

    operations = [
        migrations.AddField(
            model_name='diary',
            name='servings',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
