# Generated by Django 2.0.7 on 2018-07-26 00:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foodi', '0012_auto_20180725_2311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diary',
            name='food',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diaries', to='foodi.Food'),
        ),
        migrations.AlterField(
            model_name='diary',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diaries', to='foodi.Profile'),
        ),
    ]
